# -*- coding: utf-8 -*-
"""Capstone Project 17

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZ-oA-0I97YlLc0_GTCsk_iA-dkXPEhp

# Capstone Project 17: House Price Prediction

---

### Context

The price of the house depends on various factors like locality, connectivity, number of rooms, etc. Change in the mindset of the millennial generation also contributes to ups and down in house prices as the young generation is much into renting than to owe a house. Predicting the right price of the house is important for investors in the real estate business. This makes it very important to come up with proper and smart technique to estimate the true price of the house.

---

#### Getting Started

Follow the steps described below to solve the project:

1. Click on the link provided below to open the Colab file for this project.
   
   https://colab.research.google.com/drive/1rNOLaLj4FrAYjjuaG2cpPhky5ERhdxry?usp=sharing

2. Create the duplicate copy of the Colab file. Here are the steps to create the duplicate copy:

    - Click on the **File** menu. A new drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/0_file_menu.png' width=500>

    - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/1_create_colab_duplicate_copy.png' width=500>

     - After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_CapstoneProject17** format.

3. Now, write your code in the prescribed code cells.

---

### Problem Statement


You are willing to sell your house. You are not sure about the price of your house and want to estimate its price. You are provided with the dataset and need to make a prediction model which will help you to get a good estimate of your house for selling it.

---

### Data Description

The **housing** dataset contains the prices and other attributes. There are $545$ rows and $12$ attributes (features) with a target column (price).

Following are the features:  

|Column|Description|
|---:|:---|
|`Price`|Price in INR|
|`area`|Area in square ft.|
|`bedrooms`|Number of bedrooms in the house|
|`bathrooms`|Number of bathrooms in the house|
|`stories`|Number of stores in the house|
|`mainroad`|Whether house is on main road or not(binary)|
|`guestroom`|Whether house have guestroom or not(binary)|
|`basement`|Whether house have basement or not(binary)|
|`airconditioning`|Whether house have airconditioning or not(binary)|
|`hotwaterheating`|Whether house have hotwaterheating or not(binary)|
|`parking`|Number of parking area|
|`prefarea`|Whether house have prefarea or not(binary)|
|`furnishingstatus`|Furnish status of the house|


  **Dataset Link:**  https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/house-prices.csv

---

### Things To Do

1. Explore the Housing dataset by creating the following plots:
   - Box plots between each categorical feature and the `price`.
   - Scatter plots between the numerical features and the `price`.
   
2. Convert categorical attributes into numerical attributes using feature encoding.

3. Build a linear regression model by selecting the most relevant features to predict the price of houses.

4. Evaluate the linear regression model by calculating the parameters such as coefficient of determination, MAE, MSE, RMSE, mean of residuals and by checking for homoscedasticity.

---

#### 1. Import Modules and Load Dataset

**Dataset Link:** https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/house-prices.csv
"""

# Import the required modules and load the dataset.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,mean_squared_log_error
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.feature_selection import RFE
from scipy.stats import norm
import math as ma
import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv('https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/house-prices.csv')
df.head()

# Get the information on DataFrame.
df.info()

# Check if there are any NULL values.
df.isnull().sum()

"""---

#### 2. Exploratory Data Analysis

We need to predict the value of `price` variable, using other variables. Thus, `price` is the target or dependent variable and other columns except `price` are the features or the independent variables.

Perform the following tasks:

- Create Box plots between each **categorical** variable and the target variable `price` to sense the distribution of values.

- Create the Scatter plots between each **numerical** variable and the target variable `price`. Determine which variable(s) shows linear relationship with the target variable `price`.

- Create a normal distribution curve for the `price`.
"""

# Check categorical attributes
categori_df = df.select_dtypes(['object'])
categori_df.head()

# Boxplot for 'mainroad' vs 'price'
plt.figure(figsize=(20,5),dpi = 96)
sns.boxplot(df['mainroad'],df['price'])
plt.show()

# Boxplot for 'guestroom' vs 'price'
plt.figure(figsize=(20,5),dpi = 96)
sns.boxplot(df['guestroom'],df['price'])
plt.show()

# Boxplot for 'basement' vs 'price'
plt.figure(figsize=(20,5),dpi = 96)
sns.boxplot(df['basement'],df['price'])
plt.show()

# Boxplot for 'hotwaterheating' vs 'price'
plt.figure(figsize=(20,5),dpi = 96)
sns.boxplot(df['hotwaterheating'],df['price'])
plt.show()

# Boxplot for 'airconditioning' vs 'price'

plt.figure(figsize=(20,5),dpi = 96)
sns.boxplot(df['airconditioning'],df['price'])
plt.show()

# Boxplot for 'prefarea' vs 'price'
plt.figure(figsize=(20,5),dpi = 96)
sns.boxplot(df['prefarea'],df['price'])
plt.show()

# Boxplot for 'furnishingstatus' vs 'price'
plt.figure(figsize=(20,5),dpi = 96)
plt.title(" Boxplot for Furnishingstatus vs Price")
sns.boxplot(df['furnishingstatus'],df['price'])
plt.show()

# Create scatter plot with 'area' on X-axis and 'price' on Y-axis
plt.figure(figsize=(20,5),dpi = 96)
plt.scatter(df['area'],df['price'])
plt.show()

# Create scatter plot with 'bedrooms' on X-axis and 'price' on Y-axis
plt.figure(figsize=(20,5),dpi = 96)
plt.scatter(df['bedrooms'],df['price'])
plt.show()

# Create scatter plot with 'bathrooms' on X-axis and 'price' on Y-axis
plt.figure(figsize=(20,5),dpi = 96)
plt.scatter(df['bathrooms'],df['price'])
plt.show()

# Create scatter plot with 'stories' on X-axis and 'price' on Y-axis
plt.figure(figsize=(20,5),dpi = 96)
plt.scatter(df['stories'],df['price'])
plt.show()

# Create a normal distribution curve for the 'price'.
def prob(arr,mean,std):
    coeff = 1/(std*np.sqrt(2*np.pi))
    power=np.exp(-((arr-mean)**2/(2*(std**2))))
    return coeff*power
# Create a probablity density function for plotting the normal distribution
# Plot the normal distribution curve using plt.scatter()
rho = prob(df['price'].sort_values(),df['price'].mean(),df['price'].std())
plt.figure(figsize=(20,5))
plt.scatter(df['price'].sort_values(),rho)
plt.axvline(x = df['price'].mean(),label='mean of price')
plt.legend()
plt.show()

"""---

#### 3. Feature encoding

Perform feature encoding using `map()` function and one-hot encoding.
"""

# Replace yes with 1 and no with 0 for all the values in features 'mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea' using map() function.
words={'yes':1,'no':0}
df['mainroad'] = df['mainroad'].map(words)
df['guestroom'] = df['guestroom'].map(words)
df['basement'] = df['basement'].map(words)
df['hotwaterheating'] = df['hotwaterheating'].map(words)
df['airconditioning'] = df['airconditioning'].map(words)
df['prefarea'] = df['prefarea'].map(words)

# Print dataframe
df.head()

# Perform one hot encoding for furnishingstatus feature.
dummy_df = pd.get_dummies(df['furnishingstatus'],dtype = int, drop_first = False)
df = pd.concat([df,dummy_df],axis=1)
df.head()

# Drop 'furnishingstatus' feature
df.drop('furnishingstatus',axis = 1, inplace = True)

# Print dataframe
df.head()

"""---

#### 4. Model Building and Evaluation

Build a multiple linear regression model using the `statsmodels.api` module.
"""

# Split the 'df' Dataframe into the train and test sets.
train_df,test_df = train_test_split(df,test_size = 0.33,random_state = 42)

# Create separate data-frames for the feature and target variables for both the train and test sets.
features=list(df.columns)
features.remove('price')
X_train=train_df[features]
X_test=test_df[features]
y_train=train_df['price']
y_test=test_df['price']

# Build a linear regression model using all the features to predict prices.
X_train_sm = sm.add_constant(X_train)
lr =sm.OLS(y_train,X_train_sm).fit()
lr.params

# Print the summary of the linear regression report.
print(lr.summary())

# Calculate N and p values
rows = X_train.shape[0]
p = X_train.shape[1]
print(rows)
print(p)

# Calculate the adjusted R-square value.
r_square =lr.rsquared
adj_r_square = 1-((1- r_square)*(rows-1)/(rows-p-1))
print(adj_r_square)
print(r_square)

"""**Q:** What is the Adjusted $R^2$ value?

**A:** The adjusted $R^2$ value is 0.6740641341627107 .

---

#### 5. Model Evaluation

Build a multiple linear regression model  using `sklearn` module. Also, evaluate the model by calculating $R^2$, MSE, RMSE, and MAE values.
"""

# Build multiple linear regression model using all the features
new_lin = LinearRegression()
new_lin.fit(X_train,y_train)
y_train_pred = new_lin.predict(X_train)
y_test_pred = new_lin.predict(X_test)

# Evaluate the linear regression model using the 'r2_score', 'mean_squared_error' & 'mean_absolute_error' functions of the 'sklearn' module.
print('Train Set')
print(f'R-squared= {r2_score(y_train, y_train_pred):.3f}')
print(f'Mean Squared Error= {mean_squared_error(y_train, y_train_pred):.3f}')
print(f'Root Mean Squared Error= {np.sqrt(mean_squared_error(y_train, y_train_pred)):.3f}')
print(f'Mean Absolute Error= {mean_absolute_error(y_train, y_train_pred):.3f}')

print('Test Set')
print(f'R-squared= {r2_score(y_test, y_test_pred):.3f}')
print(f'Mean Squared Error= {mean_squared_error(y_test, y_test_pred):.3f}')
print(f'Root Mean Squared Error= {np.sqrt(mean_squared_error(y_test, y_test_pred)):.3f}')
print(f'Mean Absolute Error= {mean_absolute_error(y_test, y_test_pred):.3f}')

"""**Q:** What is the $R^2$ value for train set and test set?

**A:** The $R^2$ value for train set and test set is 0.687 and 0.658 respectively.

---

#### 6. Recursive Feature Elimination

Find out the best features out of all features using RFE and evaluate the model again.
"""

# Create a Python dictionary storing the moderately to highly correlated features with price and the corresponding correlation values.
# Keep correlation threshold to be 0.2
major_features={}
for i in features:
    cor_coef=np.corrcoef(df['price'],df[i])[0,1]
    if (cor_coef >= 0.2) or (cor_coef<= -0.2):
        major_features[i]=cor_coef
print(len(major_features))
major_features

# Perform RFE and select best 7 features
lin_reg1 = LinearRegression()
rfe1 = RFE(lin_reg1,n_features_to_select = 7)
rfe1.fit(X_train[major_features.keys()],y_train)
print(rfe1)

# Print the 7 features selected by RFE in the previous step.
rfe_features = X_train[major_features.keys()].columns[rfe1.support_]
rfe_features

# Build multiple linear regression model using all the features selected after RFE
X1 = df[rfe_features]
y1 = df['price']
# Split the DataFrame into the train and test sets such that test set has 33% of the values.

X_train,X_test,y_train,y_test=train_test_split(X1,y1,test_size = 0.33,random_state = 42)

# Build linear regression model using the 'sklearn.linear_model' module.
obj = LinearRegression()
obj.fit(X_train,y_train)

# Print the value of the intercept

print(f'{obj.intercept_:.3f}')

# Print the names of the features along with the values of their corresponding coefficients.
for i in list(zip(X1.columns.values,obj.coef_)):
  print(f'{i[0]} : {i[1]}')

# Evaluate the linear regression model using the 'r2_score', 'mean_squared_error' & 'mean_absolute_error' functions of the 'sklearn' module.
y_train_pred1 = obj.predict(X_train)
y_test_pred1 = obj.predict(X_test)

print('Train Set')
print(f'R-squared= {r2_score(y_train, y_train_pred):.3f}')
print(f'Mean Squared Error= {mean_squared_error(y_train, y_train_pred):.3f}')
print(f'Root Mean Squared Error= {np.sqrt(mean_squared_error(y_train, y_train_pred)):.3f}')
print(f'Mean Absolute Error= {mean_absolute_error(y_train, y_train_pred):.3f}')

print('Test Set')
print(f'R-squared= {r2_score(y_test, y_test_pred):.3f}')
print(f'Mean Squared Error= {mean_squared_error(y_test, y_test_pred):.3f}')
print(f'Root Mean Squared Error= {np.sqrt(mean_squared_error(y_test, y_test_pred)):.3f}')
print(f'Mean Absolute Error= {mean_absolute_error(y_test, y_test_pred):.3f}')

"""---

#### 7. Residual (Error) Analysis

Perform residual analysis to check if the residuals (errors) are normally distributed or not. For this, plot the  histogram of the residuals.
"""

# Create a histogram for the errors obtained in the predicted values for the train set.
errors1 = y_train - y_train_pred
plt.figure(figsize=(20,5),dpi=96)
plt.hist(errors1 ,bins='sturges',label=f'{errors1.mean():.3f}')
plt.axvline(errors1.mean(),color='r')
plt.legend()
plt.show()

# Create a histogram for the errors obtained in the predicted values for the test set.
errors2 = y_test - y_test_pred
plt.figure(figsize=(20,5),dpi=96)
plt.hist(errors2,bins='sturges',label=f'{errors2.mean():.3f}')
plt.axvline(errors2.mean(),color='r')
plt.legend()
plt.show()

"""---

#### 8. Verify Homoscedasticity

Check for Homoscedasticity (constant variance) by creating a scatter plot between the errors and the target variable. Determine whether there is some kind of relationship between the error and the target variable.
"""

# Create a scatter plot between the errors and the dependent variable for the train set.
plt.figure(figsize=(20,5),dpi =96)
plt.scatter(errors1,y_train,color='teal')
plt.show()

"""---

### Submitting the Project

Follow the steps described below to submit the project.

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>


3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_CapstoneProject17**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_CapstoneProject17** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""