# -*- coding: utf-8 -*-
"""Capstone Project 14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1be2nuME8pXeOzU-B6GR6VjAaewzpSpKG

# Capstone Project 14: Life Expectancy Analysis

### Context

The term **Life Expectancy** refers to the number of years a person can expect to live. It is based on an estimate of the average age of a population when they die. Life expectancy is one of the key metrics used for assessing the overall health of a population.

 The Global Health Observatory (GHO) data repository under the World Health Organization (WHO) keeps track of the health status as well as many other related factors for all countries. The data-sets are made available to the public to perform health data analysis. It has been observed that in the past 15 years, there is a huge development in the health sector resulting in the improvement of human mortality rates. The increases are nearly universal, from the richest to the poorest countries. Let's dive deeper into the life expectancy dataset and find out how different factors influence your life expectancy.

---

### Problem Statement

As the head of a leading life insurance company, your job is to formulate  global health insurance coverage plans and devise different life insurance solutions for different countries. For this, you need to obtain insightful trends and patterns in people's dying age across different countries. Also, you need to determine the factors that affect the average life expectancy of the people around the world to determine the premium rates for insurance policies.

---

#### Getting Started

Follow the steps described below to solve the project:

1. Click on the link provided below to open the Colab file for this project.
   
   https://colab.research.google.com/drive/1QNJqRN0kFplv-U8wqdy9AFzaHdFlN1xN?usp=sharing

2. Create the duplicate copy of the Colab file. Here are the steps to create the duplicate copy:

    - Click on the **File** menu. A new drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/0_file_menu.png' width=500>

    - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/1_create_colab_duplicate_copy.png' width=500>

     - After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_CapstoneProject14** format.

3. Now, write your code in the prescribed code cells.

---

### Data Description

This dataset contains life expectancy data and health factors for 193 countries from the year 2000-2015 which was collected from the WHO data repository website and its corresponding economic data was collected from the United Nation website. It consists of 22 columns and 2938 rows.

|Field|Description|
|---:|:---|
|Country|Country|
|Year|Year|
|Status|Developed or Developing|
|Life expectancy|Life Expectancy in years|
|Adult Mortality|Adult Mortality Rates of both sexes (probability of dying between 15 and 60 years per 1000 population)|
|infant deaths|Number of Infant Deaths per 1000 population|
|Alcohol|Alcohol, recorded per capita (15+) consumption|
|percentage expenditure|Expenditure on health as a percent of GDP per capita (%)|
|Hepatitis B|Hepatitis B (HepB) immunization coverage among 1-year-olds (%)|
|Measles|Measles - number of reported cases per 1000 population|
|BMI|Average Body Mass Index of the entire population|
|under-five deaths|Number of under-five deaths per 1000 population|
|Polio|Polio (Pol3) immunization coverage among 1-year-olds (%)|
|Total expenditure|General government expenditure on health (%)|
|Diphtheria|Diphtheria tetanus toxoid and pertussis (DTP3) immunization coverage among 1-year-olds (%)|
|HIV/AIDS|Deaths per 1000 live births HIV/AIDS (0-4 years)|
|GDP|Gross Domestic Product per capita (in USD)|
|Population|Population of the country|
|thinness 1-19 years|Prevalence of thinness among children and adolescents for Age 10 to 19 (%)|
|thinness 5-9 years|Prevalence of thinness among children for Age 5 to 9 (%)|
|Income composition of resources|Productive use of resources|
|Schooling|Number of years of Schooling(years)|

Here's the dataset link:

https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/life-expectancy/life-expectancy.csv

---

### Things To Do

- Rename the columns since most of them contain leading and trailing spaces. Some columns contain a few missing values. Treat them accordingly.

- Find the answer to the following questions:

  1. Is there a rise in the average life expectancy around the world in a period of 15 years, i.e., from 2000 - 2015?

  2. Do developing countries have a lower life expectancy as compared to the developed countries?
  
  3. Calculate how many countries had extremely low life expectancy, i.e., less than 60 years. List those countries.

  4. What are the most critical factors affecting life expectancy?

---

#### 1. Import Modules & Load Dataset
"""

# Import the required modules and load the dataset.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

df = pd.read_csv('https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/whitehat-ds-datasets/life-expectancy/life-expectancy.csv')
print(df.head())

# Get the information on DataFrame.
df.info()

"""**Q:** Which column(s) has/have non-numeric values?

**A:** Country and Status.

---

#### 2. Renaming Columns

Rename some columns if they contain leading and trailing spaces.
"""

# Get a list of all the columns before renaming.
df.columns

"""**Q:** Which columns contain trailing whitespaces (spaces before and after) in their names?

**A:** Life expentancy, Measles, BMI, under-five deaths, Diphtheria, HIV/AIDS, thinness 1-19 years, thinness 5-9 years.
"""

# Remove whitespaces from both ends in the column name
col_to_rename = ['Life expectancy ', 'Measles ', ' BMI ', 'under-five deaths ','Diphtheria ', ' HIV/AIDS', ' thinness  1-19 years', ' thinness 5-9 years']

for i in col_to_rename:
  df.rename(columns= {i : i.strip()}, inplace=True)

# Get list of all the columns after renaming.
df.columns

"""---

#### 3. Treat Null Values

Check for the null values in the DataFrame.
"""

# Check for the percentage null values in all the columns.
(df.isnull().sum() * 100) / df.shape[0]

"""Let's drop all the columns from the DataFrame containing more than 15% percent of the missing values.

**Q:** Which columns need to be dropped?

**A:**Hepatitis B = 18.822328, GDP = 15.248468 and population = 22.191967 are need to be dropped because they are having more than 15% of the missing value.
"""

# List of columns containing more than 15% of the missing values.
col_to_drop = ['Hepatitis B', 'GDP', 'Population']
col_to_drop

# Drop the columns containing more than 15% of the missing values.
for i in col_to_drop:
  df = df.drop(i, axis=1)

"""Replace the null values with the respective median of the columns.

**Hint:** To replace the null values with their respective median, you can use `fillna()` function. Some of the examples are:

- `df.fillna('0')` $\rightarrow$ Replaces all null values in the DataFrame `df` with `0`.

- `df.fillna('0', inplace = True)` $\rightarrow$ Here the `inplace = True` parameter instructs to replace the null values in-place i.e. directly inside the DataFrame without creating its copy. It is an optional parameter.

- `df['column_name'].fillna(df['column_name'].median(), inplace = True)` $\rightarrow$ Replaces all null values of a column with its median.





"""

# Get the columns having the null values.
df.isnull().sum()

"""Before replacing the null values, let's split our DataFrame into two separate DataFrames based on the development status of the countries."""

# Grouping the DataFrame based on the development status of countries. First get the DataFrame of the developed countries
developed_df = df[df['Status'] == 'Developed']
developed_df.head()

# Check for the null values in the developed countries DataFrame
developed_df.isnull().sum()

# Get the columns having the null values in the developed countries DataFrame
null_col = ['Alcohol', 'Total expenditure', 'Income composition of resources', 'Schooling']
null_col

# Get a descriptive statistics summary of the columns having the null values in the developed countries DataFrame
for i in null_col:
  print(i, developed_df[i].describe(), sep='\n')
  print()

# Replace the missing values of the developed countries DataFrame with the median value of the respective columns.
for i in null_col:
  developed_df.loc[developed_df[i].isnull() == True, i] = developed_df[i].median()

# Again get a descriptive statistics summary of the columns having null values in the developed countries DataFrame.
# This is done to verify that the replaced values did not disrupt the data
for i in null_col:
  print(i, developed_df[i].describe(), sep='\n')
  print()

"""**Note:** Make sure that there is no major change in the mean, std, min, 25%, 50%, 75% and max values after replacing null values."""

# Again check whether there are any missing values
developed_df.isnull().sum()

# Get the DataFrame of the developing countries
developing_df = df[df['Status'] == 'Developing']
developing_df.head()

# Check for the null values in the developing countries DataFrame
developing_df.isnull().sum()

# Get a descriptive statistics summary of the columns having the null values in the developing countries DataFrame
d_null_col = ['Life expectancy', 'Adult Mortality', 'Alcohol',
              'BMI', 'Polio', 'Total expenditure', 'Diphtheria',
              'thinness  1-19 years', 'thinness 5-9 years',
              'Income composition of resources', 'Schooling']

for i in d_null_col:
  print(i, developing_df[i].describe(), sep='\n')
  print()

# Replace the missing values of the developing countries DataFrame with the median value of the respective columns.
for i in d_null_col:
  developing_df.loc[developing_df[i].isnull() == True, i] = developing_df[i].median()

# Again get a descriptive statistics summary of the DataFrame to verify that the replaced values did not disrupt the data
for i in d_null_col:
  print(i, developing_df[i].describe(), sep='\n')
  print()

# Again check whether there are any missing values
developing_df.isnull().sum()

"""---

#### 4. Life Expectancy  w.r.t Year

Find out whether the average age of death had increased globally in a period of 15 years i.e. from the year 2000 to 2015. Create a bar plot to depict this relationship.
"""

# Life expectancy w.r.t Year using bar plot for developed countries
plt.figure(figsize=(20, 7))
plt.style.use('dark_background')
sns.barplot(x='Year', y='Life expectancy', data=developed_df)
plt.show()

# Life expectancy w.r.t Year using bar plot for developing countries
plt.figure(figsize=(20, 7))
plt.style.use('dark_background')
sns.barplot(x='Year', y='Life expectancy', data=developing_df)
plt.show()

"""**Q:** Do you find any increase in the average life expectancy over 15 years?

**A:** Yes.

**Q:** In which year, the average life expectancy was maximum?

**A:** 2015

---

#### 5. Developing versus Developed Countries

Find out whether the people living in developing countries die early as compared to those living in developed countries.
"""

# Create a barplot for yearly life expectancy of developing and developed countries in a single bar chart.
plt.figure(figsize=(20, 7))
plt.style.use('dark_background')
sns.barplot(x='Year', y='Life expectancy', data=developed_df)
sns.barplot(x='Year', y='Life expectancy', data=developing_df)
plt.show()

# Find the overall average life expectancy of developed and developing countries
developed_avg_life = developed_df['Life expectancy'].mean()
developing_avg_life = developing_df['Life expectancy'].mean()

developed_avg_life, developing_avg_life

"""**Q:** Is there a huge difference in the average life expectancies of developing and developed countries?

**A:** Yes

---

#### 6. Probability Distribution of Life Expectancy

Let us find out how many developing countries had extremely low life expectancy in the year 2015. Perform the following tasks:
- Create a line plot for the life expectancy of developing countries for the year 2015 with life expectancy on the X-axis and their corresponding probability densities on the Y-axis.

- Also, find out how many developing countries had extremely low life expectancy i.e. below 60 in the year 2015. Use $Z$-score and `cdf()` function to find the probability of the random variable $X \le 60$.

- List down the names of the developing countries that had a life expectancy below 60 years in the year 2015.


**Note:** Instead of applying the `cdf()` function, you can also use `integrate` module of the `scipy` package.
"""

# Create a Python function to calculate the individual probabilities of all the life expectancies
def probility(series, mean, std):
  prob_list = []
  for x in series:
    p = 1 / (std * (np.sqrt(2*np.pi)))
    e = np.exp((-1 / 2) * ((x-mean)/std) ** 2)
    prob_den = p * e
    prob_list.append(prob_den)

  return pd.Series(prob_list)

# Create a DataFrame of developing countries for year 2015
developing_2015 = developing_df[developing_df['Year'] == 2015]
developing_2015.head()

# Plot the probability distribution of life expectancy of developing countries for the year 2015. Also, fill the area for X < 60.

developing_2015_Life = developing_2015['Life expectancy']
developing_2015_Life_sort = developing_2015_Life.sort_values()
prob60 = probility(np.arange(developing_2015_Life.min(), 60), developing_2015_Life.mean(), developing_2015_Life.std())
df_prob = probility(developing_2015_Life_sort, developing_2015_Life.mean(), developing_2015_Life.std())

plt.style.use('dark_background')
plt.figure(figsize=(20,7))
plt.plot(developing_2015_Life_sort, df_prob)
plt.fill_between(x=np.arange(developing_2015_Life_sort.min(), 60), y1=prob60, facecolor='yellow')
plt.axvline(60, color='r')
plt.xlabel('Year')
plt.ylabel('Probility')
plt.show()

# Calculate Z-score of 60 and find P(X < 60) by applying 'cdf()' function
z = (60 - developing_2015_Life.mean()) / developing_2015_Life.std()
prob = scipy.stats.norm.cdf(z)
prob

"""

**Q:** How much percentage of developing countries had extremely low life expectancy in the year 2015?

**A:** 9.8

"""

# List down the name of the countries having life expectancy below 60 in the year 2015
x=list(developing_2015.loc[developing_2015['Life expectancy'] > 60, 'Country'])
x

"""**Q:** Which country had the lowest life expectancy in the year 2015?

**A:**Angola has the lowest life expentency as he is having expectency of 52.4 and is lowest in the chart according the life expectancy.
"""

x = developing_2015[developing_2015['Life expectancy']<60]
x

"""---

#### 7. Finding Correlation

Find the columns that are highly correlated with the `Life expectancy` column. For this, calculate the correlation coefficient values between all the columns and then use a heatmap to visualise these correlations.
"""

# calculate correlation coefficient for all columns of the original DataFrame
corr_df = df.corr()
# Use heatmap to observe correlations.
plt.style.use('dark_background')
plt.figure(figsize=(30, 10))
sns.heatmap(data=corr_df, annot=True)
plt.show()

"""**Q:** Which attribute(s) have an extremely strong **positive** correlation with `Life expectancy`?

**A:** BMI, Income composition of resources and Schooling.



**Q:** Which attribute(s) have an extremely strong **negative** correlation with `Life expectancy`?

**A:**  Adult Mortality and HIV/AIDS.




**Q:** By observing the correlation heatmap, find out other attributes or features that are highly correlated with each other (excluding Life expectancy).

**A:** Infant deaths and under-five deaths, thinness 1-19 years and thinness 5-9 years, Income compositionn of resources and schooling.

---

### Submitting the Project

Follow the steps described below to submit the project.

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>


3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_CapstoneProject14**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_CapstoneProject14** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""