# -*- coding: utf-8 -*-
"""Capstone Project 14: Payroll System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uy4VwRWuYbyiYyx6pw3KvNnXByw9HQVc

# Capstone Project 14: Payroll Calculation using OOP

### Context

**Payroll System** of any organisation calculates the amount the organisation owe to its employees based on various factors such as the time and the number of days they worked, their hourly wages or commission rate, and whether they took leave during the pay period. The system determines the gross pay by evaluating taxes and other deductions. On the payroll date, the system provides the employees with the details of payroll deposits in the form of a **pay slip**.

---

### Problem Statement


ABC Finance company hired you as a software developer. Your first assignment is to create a simple  **Payroll System** for the company to perform payroll calculations based on an employee inheritance hierarchy that meets the following requirements:

The company has **Salaried employees** and they are paid a fixed salary regardless of the number of hours they work. Their salary is calculated by adding the basic salary, TA (Travelling allowance), DA (Dearness allowance) and HRA (House rent allowance).

To make the system reusable and extensible, the system must be constructed using **object-oriented** methodology.

---

#### Getting Started

Follow the steps described below to solve the project:

1. Click on the link provided below to open the Colab file for this project.
   
   https://colab.research.google.com/drive/1IXToJjmrnNGguk8bV1frz5-UyMkaw87k

2. Create the duplicate copy of the Colab file. Here are the steps to create the duplicate copy:

    - Click on the **File** menu. A new drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/0_file_menu.png' width=500>

    - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/1_create_colab_duplicate_copy.png' width=500>

     - After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_CapstoneProject14** format.

3. Now, write your code in the prescribed code cells.

---

### Things To Do

The payroll system must be able to perform the following tasks:

 - Allow the user to input employee details such as employee ID, employee name and social security number.
 - Reject duplicate employee ID and prompt the user to enter a unique employee ID for every new employee.
 - Store the employee records temporarily in a collection.
 - Display the information of all the employees on the screen.
 - Update different employees allowances.
 - Calculate monthly earnings of the employee based on their type.

---

### 1. Create a Parent Class `Employee`.


1. Create a parent class `Employee`. The constructor of this class must initialise the following private instance variables:

  - `self.__empid = empid` : Employee ID
  -  `self.__empname = empname` : Employee Name
  - `self.__ssn = ssn` : Social Security Number

2. Also, create an instance variable `income` and initialise it to `None`.

3. Add getter and setter functions for `empid`, `empname` and `ssn`. Create getter function for `income`.

3. Create an empty function `calculate_income()` which will be used or overriden in child classes to calculate the value of `income` variable based on the type of employee.

4. Also, add a `__repr__()` function to print all the details of an employee including their calculated income.
"""

#  Create class 'Employee'. Add constructor to initialise variables. Add getter and setter functions.

# Step 1: class 'Employee'
class Employee:
  # Step 2: The '__init__()' method in the 'Employee' class.
  def __init__(self, empid, empname, ssn):
    # Store the inputs of the '__init__()' method in their instance variables.
    self.__empid = empid
    self.__empname = empname
    self.__ssn = ssn
    self.__income = 0
  # Step 3: Create the getter function 'def get_empid(self)' that returns the employee ID ('return self.__empid').
  def get_empid(self):
    # Write your code here
    return self.__empid
  # Create the getter function 'def get_empname(self)' that returns the employee name ('return self.__empname').
  def get_empname(self):
    # Write your code here
    return self.__empname
  # Create the getter function 'def get_ssn(self)' that returns the SSN ('return self.__ssn').
  def get_ssn(self):
    # Write your code here
    return self.__ssn
  # Create the getter function 'def get_income(self)' that returns the SSN ('return self.income').
  def get_income(self):
    # Write your code here
    return self.__income
  # Step 4: Create the setter function 'def set_empname(self, newname)' that updates the employee name with a new name ('self.__empname = newname').
  def set_empname(self, newname):
    # Write your code here
    self.__empname = newname
  # Step 5: Create the 'calculate_income()' function 'def calculate_income(self)' and just add 'pass' inside the function.
  def set_income(self, new_income):
    self.__income = new_income
  # Step 6: Add the '__repr__()' function in the 'Employee' class which returns the value of the 'empid', 'empname', 'ssn' and 'income' variables.
  def __repr__(self):
    # Write your code here
    return "Name: "+str(self.__empname)+", ID: "+str(self.__empid)+", SSN: "+str(self.__ssn)+", Income: "+str(self.__income)

"""---

###2. Create a Child Class `SalariedEmployee`.

1. Create a class `SalariedEmployee` that inherits from the parent class `Employee`. In addition to the properties of the parent class, the constructor of this class must initialise the following instance variables:

  - `ta`: Travelling allowance. Initialise it to any value between 500 and 1000.

  - `da`: Dearness allowance. Initialise it to any value between 500 and 1000..

  - `hra`: House rent allowance. Initialise it to any value between 500 and 1000.

2. Create getter and setter functions for each instance variable.

3. **Override** the function `calculate_income()` of the parent class `Employee`. Inside this function, ask the user to enter the basic salary and store it in the `basic` variable. Calculate the value of `income` variable in the following way:
```
income = basic + ta + da + hra
```
Return this calculated income.
"""

# Step 1: The child class 'SalariedEmployee'.
class SalariedEmployee(Employee):
  # Step 2: The '__init__()' method in the 'SalariedEmployee' class.
  def __init__(self, empid, empname, ssn):
    # Step 3: Call the parent class constructor using 'super()'
    super().__init__(empid, empname, ssn)
    # Initialise the instance variable for travelling allowance with any value ('self.__ta = 600')
    self.__ta = 500
    # Initialise the instance variable for dearness allowance with any value ('self.__da = 1000')
    self.__da = 500
    # Initialise the instance variable for house rent allowance with any value ('self.__hra = 1000')
    self.__hra = 500
    self.__income = 0
  # Create the getter function 'def get_ta(self)' that returns the SSN ('return self.__ta').
  def get_ta(self):
    # Write your code here
    return self.__ta
  # Create the getter function 'def get_hra(self)' that returns the SSN ('return self.__hra').
  def get_hra(self):
    # Write your code here
    return self.__hra
  # Create the getter function 'def get_da(self)' that returns the SSN ('return self.__da').
  def get_da(self):
    # Write your code here
    return self.__da
  # Create the setter function 'def set_ta(self, new_ta)' that updates the employee name with a new name ('self.__ta = new_ta').
  def set_ta(self,new_ta):
    # Write your code here
    self.__ta = new_ta
  # Create the setter function 'def set_da(self, new_da)' that updates the employee name with a new name ('self.__da = new_da').
  def set_da(self,new_da):
    # Write your code here
    self.__da = new_da
  # Create the setter function 'def set_hra(self, new_hra)' that updates the employee name with a new name ('self.__hra = new_hra').
  def set_hra(self,new_hra):
    # Write your code here
    self.__hra = new_hra

  # Add constructor and override 'calculate_income()' function.
  def calculate_income(self):
     # Write your code here
     basic = int(input("What's the basic salary? "))
     self.set_income(basic + self.__ta + self.__da + self.__hra)
     print(self.__income)

"""**Hint**: You can use the below code to override the `calculate_income()` function.

```
basic = int(input("Enter the basic salary: "))
self.income = basic + self.__ta + self.__da + self.__hra
return self.income
```

---

### 3. Create a Class `Management`

Create a class `Management`. We will use this class to store employee records. Inside this class, perform the following tasks:

- **Step 1**: Create an empty list `emp_id_list` which will hold only employee ID of the existing employees. Also, create another empty list `emp_records` which will hold all the employee records.

- **Step 2**: Create a function `existing_employee()` which will take `emp_id` as an input and will check whether this `emp_id` already exists in the list `emp_id_list`. If yes, then display a message `This employee ID already exists`. If it does not exists then add the new `emp_id` to the `emp_id_list`.

 ```
 def existing_employee(self,emp_id):
    for i in Management.emp_id_list:
      if i == emp_id:
        print("This employee ID already exists")
        
        return 0
    Management.emp_id_list.append(emp_id)
    return 1
 ```

- **Step 3**: Create a class method `add_records()` which accepts the current `employee` object as a parameter. Inside this method:
  - Create an empty dictionary.
  - Store all the properties of `employee` object i.e. Employee ID, Employee Name, SSN and their income in this dictionary in the form of key-value pairs.
  - Append this dictionary to the list `emp_records`.
  
  In this way, we will add the record of every new employee to the `emp_records` list.

- **Step 4**:  Create a class method `display_records()` which will display the records of all employees stored in `emp_records` list.
"""

# Create class 'Management'.
class Management:
  emp_id_list = []
  emp_records = []

  # Create 'existing_employee' function
  @classmethod
  def existing_employee(cls, emp_id):
    # Write your code here
    for i in Management.emp_id_list:
      while i == emp_id:
        print("This employee ID already exists")
        return 0
    Management.emp_id_list.append(emp_id)
    return 1
  # Create class method 'add_records()'
  @classmethod
  def add_records(cls, employee):
    # Write your code here
    employ = {}
    employ["Employee ID"]=employee.get_empid()
    employ["Employee Name"]=employee.get_empname()
    employ["SSN"]=employee.get_ssn()
    employ["Salary"]=employee.get_income()
    Management.emp_records.append(employ)
   # Create class method 'display_records()'
  @classmethod
  def display_records(cls):
    # Write your code here
    for i in Management.emp_records:
      for j in i:
        print(f"{j} : {i[j]}")
      print("------------------------------------")
    print("***************************************")

"""**Hints:**

1. You can create the `add_records()` class method using the below code,

 ```
 @classmethod
  def add_records(cls, employee):
    emp = {}
    emp['Id'] = employee.get_empid()
    emp['Name'] = employee.get_empname()
    emp['SSN'] = employee.get_ssn()
    emp['Salary'] = employee.income
    Management.emp_records.append(emp)
 ```

2. You can create the `display_records()` class method using the below code,

 ```
 @classmethod
  def display_records(cls):
    for i in Management.emp_records:
      for j in i:
        print(f"{j} : {i[j]}")
      print("------------------------------------")
    print("***************************************")
 ```

---

### 4. Creating Objects and Calling the Functions

Please execute the below code cell to create the Objects and call the Functions.
"""

# Create an infinite while loop.
while True:
  id = input("Enter employee ID: ")
  manage = Management()

  while manage.existing_employee(id) == 0:
    print("Please enter a new employee id ")
    id = input("Enter employee ID: ")
  name = input("Enter employee name: ")
  ssn = input("Enter social security number: ")

  emp1 = SalariedEmployee(id, name, ssn)

  while True:
    print(f"\nTravelling allowance is {emp1.get_ta()}\nDearness allowance is {emp1.get_da()}\nHouse Rent allowance is {emp1.get_hra()}\n")
    print("-----Enter your choice------")
    user_choice = input("Enter 1 for updating Travelling allowance(TA)\nEnter 2 for updating Dearness allowance(DA)\nEnter 3 for updating House Rent allowance(HRA)\nEnter 4 to skip updating: ")
    while user_choice not in ['1','2','3','4']:
      print("-----Please enter a valid option------")
      user_choice = input("Enter 1 for updating Travelling allowance(TA)\nEnter 2 for updating Dearness allowance(DA)\nEnter 3 for updating House Rent allowance(HRA)\nEnter 4 to skip updating: ")

    if user_choice == '1':
      new_ta = int(input("\nEnter the new Travelling Allowance: "))
      emp1.set_ta(new_ta)
      print(f"Travelling allowance is {emp1.get_ta()}\n")
    elif user_choice == '2':
      new_da = int(input("Enter the new Dearness Allowance: "))
      emp1.set_da(new_da)
      print(f"Dearness allowance is {emp1.get_da()}\n")
    elif user_choice == '3':
      new_hra = int(input("Enter the new House Rent Allowance: "))
      emp1.set_hra(new_hra)
      print(f"House Rent allowance is {emp1.get_hra()}\n")
    else:
      break
    print("----------------------------------------")

    choice = int(input("Do you wish to continue updating TA, DA or HRA?\nEnter 1 for YES\nEnter 2 for NO\n"))

    if choice == 2:
      break


  print(f"\n--------Calculating Income----------------")
  emp1.calculate_income()
  print("\n--------Employee Details----------------")
  print(emp1)
  print("\n----------------------------------------")
  Management.add_records(emp1)
  choice_display=int(input("\nView All Records?\nEnter 1 for YES\nEnter 2 for NO\n"))
  if choice_display == 1:
    print("Employee Records")
    print("\n----------------------------------------")
    Management.display_records()

  choice=int(input("\nDo you wish to continue?\nEnter 1 for YES\nEnter 2 for NO\n"))

  if choice == 2:
    print("Thank you")

    break

"""In the above code cell,

We are creating an infinite `while` loop. Inside this `while` loop, we are performing the following tasks:

1. Asking the user to enter the employee ID, employee name and social security number and store each one of them in separate variables. Also checking whether the employee ID entered by the user already exists in the records by calling the `existing_employee()` function of the `Management` object. If it exists, prompt the user to re-enter a new employee ID.

2. Creating an object of `SalariedEmployee` class, passing the employee ID, employee name and social security number as parameters while creating the object of the `SalariedEmployee` class and we are performing the following steps:

      - **Step 2.1:** Creating an infinite while loop and asking the user to enter one of the following options:
```
    Enter 1 for updating Travelling allowance(TA)
    Enter 2 for updating Dearness allowance(DA)
    Enter 3 for updating House Rent allowance(HRA)
    Enter 4 to skip updating
```
      - **Step 2.2:** Taking the user input and storing it in a variable `user_choice`. Checking whether the user entered any input other than 1, 2, 3 or 4 . If yes, then we are displaying a message `"Please enter a valid option"` and keep on asking for user input unless the user enters a valid choice.

      - **Step 2.3:** If the user enters 1, 2 or 3 we are calling the respective setter function and displaying the updated allowance. For option 4, we are breaking the inner while loop created in step 2.1 using the `break` statement.

3. Then we are asking the user whether they wish to continue the updation. If no, then we are breaking the inner `while` loop.
      
4. As a next task, we are calculating the payroll. For this, we are calling the `calculate_income()` function using the object of the child class and printing the details of the employee along with their calculated income.

5. Then we are calling the class method `add_records()` of class `Management` and passing the current employee object as input to the method.

6. Asking the user whether they wish to view the records of all employees. If yes, we are displaying the records using the class method `display_records()` of the class `Management`.

7. As a final task, we are asking the user whether they wish to continue running the application. If no, then we are breaking the infinite `while` loop after showing the **Thank you** message.

---

### Submitting the Project

Follow the steps described below to submit the project.

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>


3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_CapstoneProject14**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_CapstoneProject14** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""